// === WIZARD.JS v7 ===
let currentStep=1;
const totalSteps=4;
function selectShape(btn){document.querySelectorAll('.shape-card').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');STATE._wizardType=btn.dataset.type;}
function selectMount(btn){document.querySelectorAll('[data-mount]').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');STATE._wizardMount=btn.dataset.mount;const info=document.getElementById('anclaje-info');if(STATE._wizardMount==='anclaje'){if(info)info.style.display='block';STATE._wizardFondo=false;STATE._wizardRail=true;}else{if(info)info.style.display='none';STATE._wizardFondo=true;STATE._wizardRail=false;}}
function selectThick(btn){document.querySelectorAll('[data-thick]').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');STATE._wizardThick=parseInt(btn.dataset.thick);}
function selectPlancha(btn){document.querySelectorAll('.plancha-btn').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');STATE.planchaW=parseInt(btn.dataset.pw);STATE.planchaH=parseInt(btn.dataset.ph);}
function updatePreview(){STATE._wizardAncho=parseFloat(document.getElementById('dim-ancho').value)||90;STATE._wizardAlto=parseFloat(document.getElementById('dim-alto').value)||200;STATE._wizardProf=parseFloat(document.getElementById('dim-prof').value)||45;drawPreview(STATE._wizardAncho,STATE._wizardAlto,STATE._wizardProf);}
function drawPreview(a,h,p){const canvas=document.getElementById('preview-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const pad=28,iso=0.45;const scale=Math.min((W-pad*2-30)/Math.max(a,1),(H-pad*2-30)/Math.max(h,1));const fw=a*scale,fh=h*scale,fd=p*scale*iso;const ox=(W-fw-fd)/2,oy=(H-fh-fd)/2+fd;ctx.strokeStyle='#d4a843';ctx.lineWidth=1.5;ctx.fillStyle='rgba(212,168,67,0.07)';ctx.beginPath();ctx.rect(ox,oy,fw,-fh);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(ox,oy-fh);ctx.lineTo(ox+fd,oy-fh-fd*0.5);ctx.lineTo(ox+fw+fd,oy-fh-fd*0.5);ctx.lineTo(ox+fw,oy-fh);ctx.closePath();ctx.fillStyle='rgba(212,168,67,0.12)';ctx.fill();ctx.stroke();ctx.fillStyle='#9a9a96';ctx.font='10px Space Grotesk,sans-serif';ctx.textAlign='center';ctx.fillText(`${a}×${h}×${p}cm`,ox+fw/2,oy+16);}
function wizardNext(){if(currentStep===1&&!document.querySelector('.shape-card.selected'))document.querySelector('.shape-card').click();if(currentStep<totalSteps)goToStep(currentStep+1);else finishWizard();}
function wizardBack(){if(currentStep>1)goToStep(currentStep-1);}
function goToStep(step){document.querySelector(`.wizard-step[data-step="${currentStep}"]`).classList.remove('active');document.querySelector(`.wizard-step[data-step="${step}"]`).classList.add('active');currentStep=step;document.getElementById('btn-back').style.visibility=step>1?'visible':'hidden';document.getElementById('btn-next').textContent=step===totalSteps?'Empezar →':'Siguiente →';document.querySelectorAll('.dot').forEach((d,i)=>d.classList.toggle('active',i===step-1));if(step===3)setTimeout(()=>updatePreview(),50);}
function finishWizard(){STATE._wizardAncho=parseFloat(document.getElementById('dim-ancho').value)||90;STATE._wizardAlto=parseFloat(document.getElementById('dim-alto').value)||200;STATE._wizardProf=parseFloat(document.getElementById('dim-prof').value)||45;if(!STATE._wizardThick)STATE._wizardThick=18;if(!STATE._wizardType)STATE._wizardType='mueble-alto';if(!STATE._wizardMount)STATE._wizardMount='libre';if(STATE._wizardFondo===undefined)STATE._wizardFondo=true;document.getElementById('wizard').style.display='none';const app=document.getElementById('app');app.classList.remove('app-hidden');app.classList.add('app-visible');initApp();}
